.\"     Title: polkit-config-file-validate
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2007
.\"    Manual: polkit-config-file-validate
.\"    Source: PolicyKit
.\"
.TH "POLKIT\-CONFIG\-FILE" "1" "August 2007" "PolicyKit" "polkit-config-file-validate"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
polkit-config-file-validate - Validate a PolicyKit configuration file
.SH "SYNOPSIS"
.HP 51
\fBpolkit\-config\-file\-validate \fR\fB\fI[/path/to/config/file]\fR\fR [\fB\-\-version\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
polkit\-config\-file\-validate is used to verify that a given PolicyKit configuration file is valid\. If no path to a config file is given, the default
\fI/etc/PolicyKit/PolicyKit\.conf\fR
file will be verified\.
.PP
The typical role of this tool is to verify a configuration file before deploying it on one or more machines\.
.PP
This program exit with exit code 0 if the configuration file is valid\. If not, the program exits with a non\-zero exit code\.
.SH "OPTIONS"
.PP
\fB\-\-version\fR
.RS 4
Show version and exit\.
.RE
.PP
\fB\-\-help\fR
.RS 4
Show usage information and exit\.
.RE
.SH "BUGS"
.PP
Please send bug reports to either the distribution or the hal mailing list, see
\fI\%http://lists.freedesktop.org/mailman/listinfo/hal\fR\. to subscribe\.
.SH "SEE ALSO"
.PP

\fBPolicyKit\fR(8),
\fBPolicyKit.conf\fR(5),
\fBpolkit-policy-file-validate\fR(1)
