.\"     Title: polkit-action
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2007
.\"    Manual: polkit-action
.\"    Source: PolicyKit
.\"
.TH "POLKIT\-ACTION" "1" "August 2007" "PolicyKit" "polkit-action"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
polkit-action - List and modify registered PolicyKit actions
.SH "SYNOPSIS"
.HP 14
\fBpolkit\-action\fR [\fB\-\-action\ \fR\fB\fIaction\fR\fR] [\fB\-\-reset\-defaults\ \fR\fB\fIaction\fR\fR] [\fB\-\-show\-overrides\fR] [\fB\-\-set\-defaults\-any\ \fR\fB\fIaction\fR\fR\fB\ \fR\fB\fIvalue\fR\fR] [\fB\-\-set\-defaults\-inactive\ \fR\fB\fIaction\fR\fR\fB\ \fR\fB\fIvalue\fR\fR] [\fB\-\-set\-defaults\-active\ \fR\fB\fIaction\fR\fR\fB\ \fR\fB\fIvalue\fR\fR] [\fB\-\-version\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
polkit\-action is used to list and modify the PolicyKit actions that are registered on the system\.
.SH "OPTIONS"
.PP
\fB\-\-action \fR\fB\fIaction\fR\fR
.RS 4
Show detailed information about a specific action\.
.RE
.PP
\fB\-\-reset\-defaults \fR\fB\fIaction\fR\fR
.RS 4
Reset the defaults for the specified action to the factory defaults\. The authorization needed to do this is
\fIorg\.freedesktop\.policykit\.modify\-defaults\fR\.
.RE
.PP
\fB\-\-show\-overrides\fR
.RS 4
Prints all actions for where the defaults are overridden\.
.RE
.PP
\fB\-\-set\-defaults\-any \fR\fB\fIaction\fR\fR\fB \fR\fB\fIvalue\fR\fR
.RS 4
Override the
\fIany\fR
stanza for the given action with the supplied value\. The authorization needed to do this is
\fIorg\.freedesktop\.policykit\.modify\-defaults\fR\. Valid values for
\fIvalue\fR
are
\fIno\fR,
\fIauth_admin_one_shot\fR,
\fIauth_admin\fR,
\fIauth_admin_keep_session\fR,
\fIauth_admin_keep_always\fR,
\fIauth_self_one_shot\fR,
\fIauth_self\fR,
\fIauth_self_keep_session\fR,
\fIauth_self_keep_always\fR, and
\fIyes\fR\.
.RE
.PP
\fB\-\-set\-defaults\-inactive \fR\fB\fIaction\fR\fR\fB \fR\fB\fIvalue\fR\fR
.RS 4
Override the
\fIinactive\fR
stanza for the given action with the supplied value\. The authorization needed to do this is
\fIorg\.freedesktop\.policykit\.modify\-defaults\fR\. Valid values for
\fIvalue\fR
are
\fIno\fR,
\fIauth_admin_one_shot\fR,
\fIauth_admin\fR,
\fIauth_admin_keep_session\fR,
\fIauth_admin_keep_always\fR,
\fIauth_self_one_shot\fR,
\fIauth_self\fR,
\fIauth_self_keep_session\fR,
\fIauth_self_keep_always\fR, and
\fIyes\fR\.
.RE
.PP
\fB\-\-set\-defaults\-active \fR\fB\fIaction\fR\fR\fB \fR\fB\fIvalue\fR\fR
.RS 4
Override the
\fIactive\fR
stanza for the given action with the supplied value\. The authorization needed to do this is
\fIorg\.freedesktop\.policykit\.modify\-defaults\fR\. Valid values for
\fIvalue\fR
are
\fIno\fR,
\fIauth_admin_one_shot\fR,
\fIauth_admin\fR,
\fIauth_admin_keep_session\fR,
\fIauth_admin_keep_always\fR,
\fIauth_self_one_shot\fR,
\fIauth_self\fR,
\fIauth_self_keep_session\fR,
\fIauth_self_keep_always\fR, and
\fIyes\fR\.
.RE
.PP
\fB\-\-version\fR
.RS 4
Show version and exit\.
.RE
.PP
\fB\-\-help\fR
.RS 4
Show usage information and exit\.
.RE
.SH "COMPLETION"
.PP
PolicyKit ships with a collection of shell functions such that completion on options,
\fIaction\fR
and
\fIvalue\fR
works when using the
\fBbash\fR(1)
shell\.
.SH "BUGS"
.PP
Please send bug reports to either the distribution or the hal mailing list, see
\fI\%http://lists.freedesktop.org/mailman/listinfo/hal\fR\. to subscribe\.
.SH "SEE ALSO"
.PP

\fBPolicyKit\fR(8),
\fBPolicyKit.conf\fR(5),
\fBpolkit-auth\fR(1)
