Index: smile.pro
===================================================================
--- smile.pro.orig
+++ smile.pro
@@ -14,7 +14,8 @@ TRANSLATIONS = smile_en.ts \
 	       smile_de.ts \
 	       smile_pl.ts \
 	       smile_ru.ts \
-	       smile_pt.ts
+	       smile_pt.ts \
+	       smile_tr.ts
 
 # Input
 RESOURCES += interface.qrc
