#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2009 TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

from pisi.actionsapi import autotools
from pisi.actionsapi import pisitools
from pisi.actionsapi import shelltools
from pisi.actionsapi import get
from pisi.actionsapi import libtools
from pisi.actionsapi import texlivemodules

from pisi.actionsapi import get

WorkDir = "%s-%s" % (get.srcNAME(), get.srcVERSION().split("_")[-1])

CoreSource="texlive-%s-source" % get.srcVERSION().split('_')[-1]

def setup():
    shelltools.move("texmf", "%s/texmf" % CoreSource)
    shelltools.move("texmf-dist", "%s/texmf-dist" % CoreSource)

    shelltools.cd(CoreSource)
    libtools.libtoolize("--copy --force")

    shelltools.cd("libs/teckit/")
    shelltools.export("AT_M4DIR", ".")
    autotools.autoreconf("-fi")

    shelltools.cd("%s/%s/%s" % (get.workDIR(), WorkDir, CoreSource))

    autotools.configure(" --bindir=/usr/bin \
                          --with-system-freetype2 \
                          --with-freetype2-include=/usr/include \
                          --with-system-zlib \
                          --with-system-pnglib \
                          --without-texinfo \
                          --without-dialog \
                          --without-texi2html \
                          --disable-multiplatform \
                          --with-epsfwin \
                          --with-mftalkwin \
                          --with-regiswin \
                          --with-tektronixwin \
                          --with-unitermwin \
                          --with-ps=gs \
                          --without-psutils \
                          --without-sam2p \
                          --without-t1utils \
                          --enable-ipc \
                          --without-etex \
                          --with-xetex \
                          --without-dvipng \
                          --without-dvipdfm \
                          --without-dvipdfmx \
                          --with-xdvipdfmx \
                          --without-lcdf-typetools \
                          --without-pdfopen \
                          --without-ps2eps \
                          --without-detex \
                          --without-ttf2pk \
                          --without-tex4htk \
                          --without-cjkutils \
                          --without-xdvik \
                          --without-oxdvik \
                          --without-xindy \
                          --without-luatex \
                          --without-dvi2tty \
                          --without-vlna \
                          --disable-largefile \
                          --enable-shared \
                          --disable-static")

def build():
    shelltools.cd(CoreSource)
    autotools.make("texmf=/usr/share/texmf/")

def install():

    # Installing texmf, texmf-dist, tlpkg
    for texmf in ["texmf", "texmf-dist"]:
        shelltools.copytree("%s/%s" % (CoreSource, texmf), "%s/usr/share/%s" % (get.installDIR(), texmf))
    shelltools.copytree("tlpkg", "%s/usr/share/tlpkg" % get.installDIR())

    shelltools.cd(CoreSource)

    autotools.install("bindir=%s/usr/bin texmf=%s/usr/share/texmf/ run_texlinks=true run_mktexlsr=true" % (get.installDIR(), get.installDIR()))

    # Install documents
    docs = ["ChangeLog", "README", "BUGS", "NEWS", "README.14m", "PROJECTS"]
    dirs = ["kpathsea", "dviljk", "dvipsk", "makeindexk", "ps2pkm", "web2c"]

    pisitools.dodoc("texk/ChangeLog", "texk/README")
    for d in docs:
        for dir in dirs:
            if shelltools.can_access_file("%s/texk/%s/%s" % (get.curDIR(), dir, d)):
                pisitools.insinto("usr/share/doc/%s/texk/%s" % (get.srcNAME(), dir) , "texk/%s/%s" % (dir, d))

    # Remove these directories
    pisitools.removeDir("/usr/share/texmf/doc")
    pisitools.removeDir("/usr/share/texmf-dist/doc")

    for d in ["web2c", "updmap.d", "fmtutil.d", "texmf.d", "language.dat.d", "language.def.d"]:
        pisitools.dodir("/etc/texmf/%s" % d)

    # Remove those as they will be regenerated by texmf-update
    pisitools.remove("/usr/share/texmf/web2c/fmtutil.cnf")
    pisitools.remove("/usr/share/texmf/web2c/texmf.cnf")

    pisitools.domove("/usr/share/texmf/web2c/updmap.cfg","/etc/texmf/updmap.d/", "00updmap.cfg")
    pisitools.dodir("/etc/texmf/dvips.d")
    pisitools.dodir("/etc/texmf/dvips/config")
    pisitools.domove("/usr/share/texmf/dvips/config/config.ps", "/etc/texmf/dvips.d/", "00%s-config.ps" % get.srcNAME())

    # Create symlinks from format to engines
    texlivemodules.createSymlinksFormat2Engines()

    # Handle config files
    shelltools.cd("%s/usr/share/texmf" % get.installDIR())
    texlivemodules.handleConfigFiles(".", "cfg", "cnf")

    pisitools.dodir("/usr/share/texmf-site")

    # Symlinks for regenerated files by texmf-update
    for sym in ["fmtutil.cnf", "texmf.cnf", "updmap.cfg"]:
        pisitools.dosym("/etc/texmf/web2c/%s" % sym, "/usr/share/texmf/web2c/%s" % sym)
    pisitools.dosym("/etc/texmf/dvips/config/config.ps", "/usr/share/dvips/config/config.ps")
    pisitools.dosym("tex", "/usr/bin/virtex")
    pisitools.dosym("pdftex", "/usr/bin/pdfvirtex")

    pisitools.dodir("/var/lib/texmf")

    # Rename mpost to leave room for mplib
    pisitools.domove("/usr/bin/mpost", "/usr/bin/", "mpost-%s" % get.srcNAME())
    pisitools.dosym("mpost-%s" % get.srcNAME(), "/usr/bin/mpost")

