diff -up acpid-1.0.8/Makefile.makefile acpid-1.0.8/Makefile
--- acpid-1.0.8/Makefile.makefile	2008-10-29 04:48:52.000000000 +0100
+++ acpid-1.0.8/Makefile	2008-11-11 15:19:21.000000000 +0100
@@ -23,7 +23,8 @@ all_SRCS = $(acpid_SRCS) $(acpi_listen_S
 MAN8 = acpid.8 acpi_listen.8
 MAN8GZ = $(MAN8:.8=.8.gz)
 
-CFLAGS = -W -Wall -Werror -Wundef -Wshadow -D_GNU_SOURCE -O2 -g $(DEFS)
+CFLAGS += -W -Wall -Werror -Wundef -Wshadow -D_GNU_SOURCE $(DEFS) -fPIE
+LDFLAGS += -pie
 DEFS = -DVERSION="\"$(VERSION)\""
 
 all: $(PROGS)
