#!/bin/bash

# Disable USB autosuspend for scanners
if [ -n "${HAL_PROP_LINUX_SYSFS_PATH}" -a -e "${HAL_PROP_LINUX_SYSFS_PATH}/power/level" ]; then
    echo on > "${HAL_PROP_LINUX_SYSFS_PATH}/power/level"
fi
