pref("network.protocol-handler.app.ftp","firefox");
pref("network.protocol-handler.app.http","firefox");
pref("network.protocol-handler.app.https","firefox");
pref("mail.content_disposition_type", 1);
pref("mailnews.reply_header_type", 3);
pref("mailnews.reply_header_authorwrote", "%s şöyle yazmıştı:");
pref("mailnews.reply_header_ondate", "on %s");
pref("mailnews.reply_header_separator", " ");
pref("mailnews.reply_header_colon", ":");
pref("mailnews.default_sort_type", 2);
pref("mailnews.default_sort_order", 22);

pref("mail.compose.max_recycled_windows", 1);
pref("browser.display.show_image_placeholders", false);
pref("mailnews.customHeaders", "List-Id");

pref("general.useragent.vendor", "Pardus");
pref("general.useragent.vendorSub", "Corporate2");

pref("font.name.monospace.null", "DejaVu Sans Mono");
pref("font.name.monospace.tr", "DejaVu Sans Mono");
pref("font.name.monospace.x-central-euro", "DejaVu Sans Mono");
pref("font.name.monospace.x-unicode", "DejaVu Sans Mono");
pref("font.name.monospace.x-user-def", "DejaVu Sans Mono");
pref("font.name.monospace.x-western", "DejaVu Sans Mono");
pref("font.name.sans-serif.null", "DejaVu Sans");
pref("font.name.sans-serif.tr", "DejaVu Sans");
pref("font.name.sans-serif.x-central-euro", "DejaVu Sans");
pref("font.name.sans-serif.x-unicode", "DejaVu Sans");
pref("font.name.sans-serif.x-user-def", "DejaVu Sans");
pref("font.name.sans-serif.x-western", "DejaVu Sans");
pref("font.name.serif.tr", "DejaVu Sans");
pref("font.name.serif.x-central-euro", "DejaVu Sans");
pref("font.name.serif.x-unicode", "DejaVu Sans");
pref("font.name.serif.x-user-def", "DejaVu Sans");
pref("font.name.serif.x-western", "DejaVu Sans");
pref("font.minimum-size.null", 12);
pref("font.minimum-size.x-central-euro", 12);
pref("font.minimum-size.x-unicode", 12);
pref("font.minimum-size.x-user-def", 12);
pref("font.minimum-size.x-western", 12);
pref("font.minimum-size.tr", 12);
pref("font.size.fixed.null", 12);
pref("font.size.variable.x-unicode", 12);
pref("font.size.variable.null", 12);
pref("font.size.variable.x-western", 12);
pref("font.size.variable.tr", 12);
