#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2009-2011 TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

# Creates a simple DB for timezone lookups
# Ozan Caglayan <ozan_at_pardus.org.tr> 2009-2011

import os
import sys
import cPickle
from hashlib import sha1


oldwd = os.getcwd()
os.chdir(sys.argv[1])

zones = []
zonedict = {}
try:
    zones = [l.split()[2] for l in open("usr/share/zoneinfo/zone.tab", "r").readlines() if l and not l.startswith("#")]
except IOError:
    pass
else:
    for zone in zones:
        zonedict[sha1(open("usr/share/zoneinfo/%s" % zone, "r").read()).hexdigest()] = zone

    if zonedict:
        cp = cPickle.Pickler(open("usr/share/zoneinfo/zoneinfo.dict", "wb"), protocol=2)
        cp.dump(zonedict)

os.chdir(oldwd)
