Index: usb-modeswitch-1.1.2/Makefile
===================================================================
--- usb-modeswitch-1.1.2.orig/Makefile
+++ usb-modeswitch-1.1.2/Makefile
@@ -21,11 +21,10 @@ clean:
 	$(RM) usb_modeswitch
 
 install: all
-	install -d $(SBINDIR)
-	install --mode=755 usb_modeswitch $(SBINDIR)/usb_modeswitch
-	install --mode=755 usb_modeswitch.tcl $(UDEVDIR)/usb_modeswitch
-	install --mode=644 usb_modeswitch.conf $(ETCDIR)/usb_modeswitch.conf
-	install --mode=644 usb_modeswitch.1 $(MANDIR)/usb_modeswitch.1
+	install -D --mode=755 usb_modeswitch $(SBINDIR)/usb_modeswitch
+	install -D --mode=755 usb_modeswitch.tcl $(UDEVDIR)/usb_modeswitch
+	install -D --mode=644 usb_modeswitch.conf $(ETCDIR)/usb_modeswitch.conf
+	install -D --mode=644 usb_modeswitch.1 $(MANDIR)/usb_modeswitch.1
 
 
 uninstall:
