#!/bin/sh

WHO=`/usr/bin/whoami`
NODE=ejabberd
HOST=localhost

if [ $WHO != "ejabberd" ]; then 
  echo "ejabberdctl must be called via ejabberd user. (sudo -u ejabberd ejabberdctl)"; 
  exit 0; 
fi

# Define ejabberd environment
export HOME=/var/lib/ejabberd
export SASL_LOG_PATH=/var/log/ejabberd/sasl.log
export EJABBERD_DB=/var/lib/ejabberd/db/$NODE
export EJABBERD_EBIN=/usr/lib/ejabberd/ebin/
export ERL_INETRC=/etc/ejabberd/inetrc
export EJABBERD_LOG_PATH=/var/log/ejabberd/ejabberd.log
export EJABBERD_CONFIG_PATH=/etc/ejabberd/ejabberd.cfg
export EJABBERD_MSGS_PATH=/usr/lib/ejabberd/priv/msgs
export EJABBERD_SO_PATH=/usr/lib/ejabberd/priv/lib
export EJABBERD_BIN_PATH=/usr/lib/ejabberd/priv/bin
export ERL_MAX_PORTS=32000

[ -d $EJABBERD_DB ] || mkdir -p $EJABBERD_DB

cd /var/lib/ejabberd

function start
{
    erl -noinput -detached \
        -sname $NODE@$HOST -pa $EJABBERD_EBIN \
        -mnesia dir "\"$EJABBERD_DB\"" \
        -s ejabberd -ejabberd config \"$EJABBERD_CONFIG_PATH\" log_path \"$EJABBERD_LOG_PATH\" \
        -sasl sasl_error_logger \{file,\"$SASL_LOG_PATH\"\}
}

function debug
{
    erl \
      -sname debug$NODE@$HOST \
      -pa $EJABBERD_EBIN \
      -mnesia dir "\"$EJABBERD_DB\"" \
      -remsh $NODE@$HOST
}

function ctl
{
    erl \
      -noinput \
      -sname ejabberdctl@$HOST \
      -pa $EJABBERD_EBIN \
      -s ejabberd_ctl -extra $NODE@$HOST $@
}

function usage
{
    ctl
    exit
}

[ $# -lt 1 ] && usage

case $1 in
    start) start;;
    debug) debug;;
    *) ctl $@;;
esac

