Index: pycups-1.9.45/Makefile
===================================================================
--- pycups-1.9.45.orig/Makefile
+++ pycups-1.9.45/Makefile
@@ -9,7 +9,7 @@ DIST=Makefile test.py \
 	COPYING NEWS README TODO ChangeLog
 
 cups.so: $(SOURCES)
-	CFLAGS=-DVERSION=\\\"$(VERSION)\\\" python setup.py build
+	CC= CFLAGS=-DVERSION=\\\"$(VERSION)\\\" python setup.py build
 	mv build/lib*/$@ .
 
 doc:	cups.so
