Index: system-config-printer-1.2git/Makefile.in
===================================================================
--- system-config-printer-1.2git.orig/Makefile.in
+++ system-config-printer-1.2git/Makefile.in
@@ -1103,7 +1103,7 @@ info: info-recursive
 
 info-am:
 
-install-data-am: install-dbusDATA install-desktopDATA install-man \
+install-data-am: install-dbusDATA install-man \
 	install-nobase_pkgdataDATA install-nobase_pkgdataSCRIPTS \
 	install-udevhelperPROGRAMS install-udevhelperSCRIPTS \
 	install-udevrulesDATA
