.\"     Title: polkit-policy-file-validate
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: August 2007
.\"    Manual: polkit-policy-file-validate
.\"    Source: PolicyKit
.\"
.TH "POLKIT\-POLICY\-FILE" "1" "August 2007" "PolicyKit" "polkit-policy-file-validate"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
polkit-policy-file-validate - Validate a PolicyKit policy file
.SH "SYNOPSIS"
.HP 41
\fBpolkit\-policy\-file\-validate \fR\fB\fIpolicy\-files\fR\fR [\fB\-\-version\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
polkit\-policy\-file\-validate is used to verify that one or more PolicyKit
\fI\.policy\fR
files are valid\.
.PP
Normally this tool is used in the software release process (typically during
\fI"make check"\fR) and during software installation (e\.g\. in the
\fI%post\fR
section of a RPM spec file)\.
.PP
This program exit with exit code 0 if all the files validate\. If not, the program exits with a non\-zero exit code\.
.SH "OPTIONS"
.PP
\fB\-\-version\fR
.RS 4
Show version and exit\.
.RE
.PP
\fB\-\-help\fR
.RS 4
Show usage information and exit\.
.RE
.SH "BUGS"
.PP
Please send bug reports to either the distribution or the hal mailing list, see
\fI\%http://lists.freedesktop.org/mailman/listinfo/hal\fR\. to subscribe\.
.SH "SEE ALSO"
.PP

\fBPolicyKit\fR(8),
\fBPolicyKit.conf\fR(5),
\fBpolkit-config-file-validate\fR(1)
