#! /bin/sh

. "${PM_FUNCTIONS}"

get_pulse_users() {
    echo $(ps aux | awk '/[p]ulseaudio -D/ {print $1}')
}

suspend_pulse() {
    for i in $(get_pulse_users); do
        echo 'suspend 1' | sudo -u $i pacmd &> /dev/null
    done
}

resume_pulse() {
    for i in $(get_pulse_users); do
        echo 'suspend 0' | sudo -u $i pacmd &> /dev/null
    done
}

case $1 in
    hibernate|suspend)
        suspend_pulse
        ;;
    thaw|resume)
        resume_pulse
        ;;
    *) exit $NA
        ;;
esac
